improving validations

diff --git a/plugins/finder b/plugins/finder
--- a/plugins/finder
+++ b/plugins/finder
@@ -10,9 +10,11 @@ help(){
       m finder showhiddenfiles           # get the current status
       m finder showhiddenfiles YES       # show hidden files
       m finder showhiddenfiles NO        # don't show hidden files
+
       m finder showextensions            # get the current status
       m finder showextensions YES        # show all file extensions
       m finder showextensions NO         # don't show all file extensions
+
       m finder showdesktop               # get the current desktop status
       m finder showdesktop YES           # enable the desktop
       m finder showdesktop NO            # disable the desktop
@@ -30,18 +32,22 @@ hidden_files(){
             defaults write com.apple.finder AppleShowAllFiles -bool false
             ;;
         *)
-            HIDDEN_FILE_STATUS=$(defaults read com.apple.finder AppleShowAllFiles 2>/dev/null | tr '[:upper:]' '[:lower:]')
-            if \
-              [ -z "$HIDDEN_FILE_STATUS" ] || \
-              [ "$HIDDEN_FILE_STATUS" = "false" ] || \
-              [ "$HIDDEN_FILE_STATUS" = "no" ] || \
-              [ "$HIDDEN_FILE_STATUS" -eq 0 ] ; then
-                HIDDEN_FILE_STATUS_WORD="NO"
-            else
-                HIDDEN_FILE_STATUS_WORD="YES"
-            fi
-            echo "Show hidden files: $HIDDEN_FILE_STATUS_WORD"
-            exit 1
+            HIDDEN_FILE_STATUS=$(defaults read com.apple.finder AppleShowAllFiles 2>/dev/null)
+
+            case $HIDDEN_FILE_STATUS in
+                0|[nN][oO]|[fF][aA][lL][sS][eE])
+                    HIDDEN_FILE_STATUS="NO"
+                    ;;
+                1|[yY][eE][sS]|[tT][rU][eE])
+                    HIDDEN_FILE_STATUS="YES"
+                    ;;
+                *)
+                    echo "We can't read AppleShowAllFiles property" && exit 1
+                    ;;
+            esac
+
+            echo "Show hidden files: $HIDDEN_FILE_STATUS"
+            exit 0
             ;;
     esac
     killall Finder
@@ -58,18 +64,20 @@ file_extensions(){
             defaults write NSGlobalDomain AppleShowAllExtensions -bool false
             ;;
         *)
-            EXTENSION_STATUS=$(defaults read NSGlobalDomain AppleShowAllExtensions 2>/dev/null | tr '[:upper:]' '[:lower:]')
-            if \
-              [ -z "$EXTENSION_STATUS" ] || \
-              [ "$EXTENSION_STATUS" = "false" ] || \
-              [ "$EXTENSION_STATUS" = "no" ] || \
-              [ "$EXTENSION_STATUS" -eq 0 ] ; then
-                EXTENSION_STATUS_WORD="NO"
-            else
-                EXTENSION_STATUS_WORD="YES"
-            fi
-            echo "Show file extensions: $EXTENSION_STATUS_WORD"
-            exit 1
+            EXTENSION_STATUS=$(defaults read NSGlobalDomain AppleShowAllExtensions 2>/dev/null)
+            case $EXTENSION_STATUS in
+                0|[nN][oO]|[fF][aA][lL][sS][eE])
+                    EXTENSION_STATUS="NO"
+                    ;;
+                1|[yY][eE][sS]|[tT][rU][eE])
+                    EXTENSION_STATUS="YES"
+                    ;;
+                *)
+                    echo "We can't read AppleShowAllExtension property" && exit 1
+                    ;;
+            esac
+            echo "Show file extensions: $EXTENSION_STATUS"
+            exit 0
             ;;
     esac
     killall Finder
@@ -86,17 +94,19 @@ desktop(){
             defaults write com.apple.finder CreateDesktop -bool false
             ;;
         *)
-            DESKTOP_STATUS=$(defaults read com.apple.finder CreateDesktop 2>/dev/null | tr '[:upper:]' '[:lower:]')
-            if \
-              [ -z "$DESKTOP_STATUS" ] || \
-              [ "$DESKTOP_STATUS" = "true" ] || \
-              [ "$DESKTOP_STATUS" = "yes" ] || \
-              [ "$DESKTOP_STATUS" -eq 1 ] ; then
-                DESKTOP_STATUS_WORD="enabled"
-            else
-                DESKTOP_STATUS_WORD="enabled"
-            fi
-            echo "Desktop: $DESKTOP_STATUS_WORD"
+            DESKTOP_STATUS=$(defaults read com.apple.finder CreateDesktop 2>/dev/null)
+            case $DESKTOP_STATUS in
+                0|[nN][oO]|[fF][aA][lL][sS][eE])
+                    DESKTOP_STATUS="disabled"
+                    ;;
+                1|[yY][eE][sS]|[tT][rU][eE])
+                    DESKTOP_STATUS="enabled"
+                    ;;
+                *)
+                    echo "We can't read CreateDesktop property" && exit 1
+                    ;;
+            esac
+            echo "Desktop: $DESKTOP_STATUS"
             ;;
     esac
     killall Finder
